learning_login/basic_app/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
   
    path('registration/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

learning_login/learning_login/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

learning_login/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class userprofileinfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

learning_login/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import userprofileinfo

class userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','email','password')


class userprofileinfoform(forms.ModelForm):
    class Meta():
    
        model = userprofileinfo
        fields = ('portfolio_site','profile_pic')

   

learning_login/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import userform,userprofileinfoform
# Create your views here.

#from django.core.urlresolvers import reverse # type: ignore
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse




def index(request):
    return render(request,'basic_app/index.html')

@ login_required
def special(request):
    return HttpResponse('you are login , nice')

@ login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == "POST":
        user_form = userform(data=request.POST)
        profile_form = userprofileinfoform(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.error_class)
        
    else:
        user_form= userform()
        profile_form = userprofileinfoform()
       
        
    return render(request,'basic_app/registration.html',
                 {'user_form':user_form,
                  'profile_form':profile_form,
                  'registered':registered} )






def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)


        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse('account not active')
            
        else:
            print('someone tried to login and failed')
            print('username: {} and password: {}'.format(username,password))
            return HttpResponse('invalid login details supplied!')
    
    else:
        return render(request, 'basic_app/login.html')

learning_login/templates/basic_app/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
   
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    {% block extra_css %}
    {% endblock extra_css %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" >
</head>
<body >
  
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
       <div class="container-fluid">
         <ul class="nav navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">brand name</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">admin</a></li>
            <li class="nav-item"><a class="nav-link" href="#">hiii</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">registration</a></li>
          
        {% if user.is_authenticated %}

            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">logout</a></li>

        {% else %}
            
            <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:user_login' %}">login</a></li>
        {% endif %}
          
        </ul>
       </div>
    </nav>

    <div class="container">
        {% block body_block %}
       <!--INSIDE THIS WE CAN PUT OTHER HTML  FILES-->
       
       {% endblock %}
    </div>
</body>
</html>

learning_login/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"  %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}


{% block body_block %}

    
<div class="jumbotron text-center">
    <h1>This is the Index Page</h1>
    <p class="lead">Welcome to the home page of our Django application!</p>
</div>
   
{% endblock %}

learning_login/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    <h1>  please login here</h1>

<form action="{% url 'basic_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for=" username">username:</label>
    <input type="text" name="username" placeholder=" enterusername">

    <label for=" password">password:</label>
    <input type="password" name="password" >

    <input type="submit" value="login">



</form>


</div>

{% endblock %}

learning_login/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block body_block %}

    
    <div class="jumbotron">
      {% if registered%}
       <h1>thany for registration</h1>
      {% else %}
      <h1> register here!</h1>
      <h3>fill the form </h3>
      
      <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form }}
      {{ profile_form }}
      <input type="submit" name="" value="register">
      </form>
      {% endif %}
    </div>
    
{% endblock %}